
spring:
  datasource:
    url: jdbc:mysql://47.110.255.17:3306/fusedb?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: fuse
    password: fuse59@
    driver-class-name: com.mysql.cj.jdbc.Driver

    # druid config
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  # redis
  redis:
    host: 47.110.255.17
    port: 6379
    password: 30VpzaBN1
    timeout: 10000
  # mongo
  data:
    mongodb:
      uri: mongodb://cafl:cArfinAncia1@47.110.255.17:27017/fuse
  # activeMq
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false
# ORM
mybatis:
  type-aliases-package: com.fuse.artemis.api.db.entity
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
